# Base image
FROM python:3.12.3-slim-bookworm AS base

# Install curl, and build-essential
RUN apt update
RUN apt install -y curl build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN addgroup --system --gid 1001 system \
    && adduser --system --uid 1001 app

# Backend Build
WORKDIR /app/api
COPY ./apps/api/poetry.lock* ./
COPY ./apps/api/pyproject.toml ./
RUN pip install --upgrade pip \
    && pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# Run the backend

WORKDIR /app/api
COPY ./apps/api ./
RUN ls -lah
COPY ./production_config.yaml ./config/config.yaml

WORKDIR /app/

COPY ./extra/start.sh /app/start.sh

WORKDIR /app/api

CMD ["python3", "app.py"]
