services:
    #
    #
    #
    #########################
    # WORKSPACE 1
    #########################
    #
    #
    #
    sk-workspace-redis:
        image: redis:latest
        container_name: sk-workspace-redis
        restart: always
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 4s
            retries: 5
        volumes:
            - ./workspace_redis_data:/data

    sk-workspace-caddy:
        container_name: sk-workspace-caddy
        image: ghcr.io/sokrates-ai/sk-workspace-caddy:latest
        restart: unless-stopped
        environment:
            - "SK_BACKEND_HOST=http://sk-workspace-backend"
            - "SK_BACKEND_PORT=8000"
            - "SK_FRONTEND_HOST=http://sk-workspace-frontend"
            - "SK_FRONTEND_PORT=3000"
        ports:
            - 7001:80
        depends_on:
            - sk-workspace-backend
            - sk-workspace-frontend

    sk-workspace-frontend:
        container_name: sk-workspace-fe
        image: ghcr.io/sokrates-ai/sk-workspace-fe:latest
        restart: unless-stopped

    sk-workspace-backend:
        container_name: sk-workspace-be
        image: ghcr.io/sokrates-ai/sk-workspace-be:latest
        restart: unless-stopped
        env_file:
            - ./.workspace.env
        environment:
            - PLATFORM_HOST=sk-platform
            - PLATFORM_PORT=80

            - REDIS_HOST=sk-workspace-redis
            - REDIS_PORT=6379

            - RATE_LIMIT_SECONDS=10
            - IMAGE_UPLOAD_PATH=/uploads
        volumes:
          - ./workspace_images:/uploads
        depends_on:
            - sk-workspace-redis

    #
    #
    #
    #########################
    # PLATFORM
    #########################
    #
    #
    #
    sk-platform:
      container_name: sk-platform
      image: ghcr.io/sokrates-ai/sk-platform:latest
      ports:
        - "8000:80"
      volumes:
        - ./learnhouse_data:/usr/learnhouse
      env_file:
        - ./extra/example-learnhouse-conf.env
      environment:
        - LEARNHOUSE_WORKSPACE_API_HOST=sk-workspace-backend
        - LEARNHOUSE_WORKSPACE_API_PORT=8000
        - LEARNHOUSE_WORKSPACE_EXTERNAL_BASE_URL=http://localhost:7001
      depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy
    db:
      image: postgres:16-alpine
      restart: always
      environment:
        - POSTGRES_USER=learnhouse
        - POSTGRES_PASSWORD=learnhouse
        - POSTGRES_DB=learnhouse
      volumes:
        - ./platform_postgres:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U learnhouse"]
        interval: 5s
        timeout: 4s
        retries: 5
    redis:
      image: redis:7.2.3
      restart: always
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 4s
        retries: 5
      volumes:
          - ./platform_redis:/data
    chromadb:
      image: chromadb/chroma:0.5.16