export const SPRITES = [
  { scale: 1, file: 'Bahnhof v1.webp', label: 'Bahnhof v1' },
  { scale: 1, file: 'Bahnhof v2.webp', label: 'Bahnhof v2' },
  { scale: 1, file: 'Bank 2.webp', label: 'Bank 2' },
  { scale: 1, file: 'Bank.webp', label: 'Bank' },
  { scale: 1, file: 'Baum 1.webp', label: 'Baum 1' },
  { scale: 1, file: 'Baum 1b.webp', label: 'Baum 1b' },
  { scale: 1, file: 'Baum 2.webp', label: 'Baum 2' },
  { scale: 1, file: 'Baum 2b.webp', label: 'Baum 2b' },
  { scale: 1, file: 'Baum 3_1.webp', label: 'Baum 3_1' },
  { scale: 1, file: 'Baum 3_2.webp', label: 'Baum 3_2' },
  { scale: 1, file: 'Baum 3_3.webp', label: 'Baum 3_3' },
  { scale: 1, file: 'Baum 4 b.webp', label: 'Baum 4 b' },
  { scale: 1, file: 'Baum 4 c.webp', label: 'Baum 4 c' },
  { scale: 1, file: 'Baum 4.webp', label: 'Baum 4' },
  { scale: 1, file: 'Blume weiß 1.webp', label: 'Blume weiß 1' },
  { scale: 1, file: 'Blume weiß 2.webp', label: 'Blume weiß 2' },
  { scale: 1, file: 'Blume weiß lose.webp', label: 'Blume weiß lose' },
  { scale: 1, file: 'Blumen weiß lose.webp', label: 'Blumen weiß lose' },
  { scale: 1, file: 'Busch 1.webp', label: 'Busch 1' },
  { scale: 1, file: 'Busch 2.webp', label: 'Busch 2' },
  { scale: 1, file: 'Gebäude K.webp', label: 'Gebäude K' },
  { scale: 1, file: 'Gras 1.webp', label: 'Gras 1' },
  { scale: 1, file: 'Gras 10 groß.webp', label: 'Gras 10 groß' },
  { scale: 1, file: 'Gras 11.webp', label: 'Gras 11' },
  { scale: 1, file: 'Gras 12 k.webp', label: 'Gras 12 k' },
  { scale: 1, file: 'Gras 13 k.webp', label: 'Gras 13 k' },
  { scale: 1, file: 'Gras 2.webp', label: 'Gras 2' },
  { scale: 1, file: 'Gras 3.webp', label: 'Gras 3' },
  { scale: 1, file: 'Gras 4.webp', label: 'Gras 4' },
  { scale: 1, file: 'Gras 5 k.webp', label: 'Gras 5 k' },
  { scale: 1, file: 'Gras 6 k.webp', label: 'Gras 6 k' },
  { scale: 1, file: 'Gras 7 k.webp', label: 'Gras 7 k' },
  { scale: 1, file: 'Gras 8 k.webp', label: 'Gras 8 k' },
  { scale: 1, file: 'Gras 9 k.webp', label: 'Gras 9 k' },
  { scale: 1, file: 'Gras Fleck 1.webp', label: 'Gras Fleck 1' },
  { scale: 1, file: 'Gras Fleck 2.webp', label: 'Gras Fleck 2' },
  { scale: 1, file: 'Gras Fleck Kreis.webp', label: 'Gras Fleck Kreis' },
  { scale: 1, file: 'Gras Fleck Rechteck.webp', label: 'Gras Fleck Rechteck' },
  { scale: 1, file: 'Gras trocken.webp', label: 'Gras trocken' },
  { scale: 1, file: 'Gras trocken_2.webp', label: 'Gras trocken_2' },
  { scale: 1, file: 'Grasblume_gelb_1.webp', label: 'Grasblume_gelb_1' },
  { scale: 1, file: 'Grasblume_gelb_2.webp', label: 'Grasblume_gelb_2' },
  { scale: 1, file: 'Grasblume_gelb_3.webp', label: 'Grasblume_gelb_3' },
  { scale: 1, file: 'Grasblume_gelb_4.webp', label: 'Grasblume_gelb_4' },
  { scale: 1, file: 'Grasblume_orange_1.webp', label: 'Grasblume_orange_1' },
  { scale: 1, file: 'Grasblume_orange_2.webp', label: 'Grasblume_orange_2' },
  { scale: 1, file: 'Grasblume_orange_3.webp', label: 'Grasblume_orange_3' },
  { scale: 1, file: 'Grasblume_orange_4.webp', label: 'Grasblume_orange_4' },
  { scale: 1, file: 'Grasblume_rot_1.webp', label: 'Grasblume_rot_1' },
  { scale: 1, file: 'Grasblume_rot_2.webp', label: 'Grasblume_rot_2' },
  { scale: 1, file: 'Grasblume_rot_3.webp', label: 'Grasblume_rot_3' },
  { scale: 1, file: 'Grasblume_rot_4.webp', label: 'Grasblume_rot_4' },
  { scale: 1, file: 'Grasblume_weiß_1.webp', label: 'Grasblume_weiß_1' },
  { scale: 1, file: 'Grasblume_weiß_2.webp', label: 'Grasblume_weiß_2' },
  { scale: 1, file: 'Grasblume_weiß_3.webp', label: 'Grasblume_weiß_3' },
  { scale: 1, file: 'Grasblume_weiß_4.webp', label: 'Grasblume_weiß_4' },
  { scale: 1, file: 'Grasbüschel.webp', label: 'Grasbüschel' },
  { scale: 1, file: 'Komischer Block.webp', label: 'Komischer Block' },
  { scale: 1, file: 'Löwenzahn lose.webp', label: 'Löwenzahn lose' },
  { scale: 1, file: 'Löwenzahn.webp', label: 'Löwenzahn' },
  { scale: 1, file: 'Mr Net Transparenz Fleckig größer.webp', label: 'Mr Net Transparenz Fleckig größer' },
  { scale: 1, file: 'Mr Net Transparenz Flecking.webp', label: 'Mr Net Transparenz Flecking' },
  { scale: 1, file: 'Mr Net Tranzparenz Fläche.webp', label: 'Mr Net Tranzparenz Fläche' },
  { scale: 1, file: 'Mr Net keine transparenz.webp', label: 'Mr Net keine transparenz' },
  { scale: 1, file: 'Mülleimer.webp', label: 'Mülleimer' },
  { scale: 1, file: 'Nebel fläche 1.webp', label: 'Nebel fläche 1' },
  { scale: 1, file: 'Nebel fläche 2.webp', label: 'Nebel fläche 2' },
  { scale: 1, file: 'Nebel fläche 3.webp', label: 'Nebel fläche 3' },
  { scale: 1, file: 'Nebel klein 1.webp', label: 'Nebel klein 1' },
  { scale: 1, file: 'Nebel klein 2.webp', label: 'Nebel klein 2' },
  { scale: 1, file: 'Nebel klein 3.webp', label: 'Nebel klein 3' },
  { scale: 1, file: 'Nebel klein 4.webp', label: 'Nebel klein 4' },
  { scale: 1, file: 'Nebel v1_2 dicht.webp', label: 'Nebel v1_2 dicht' },
  { scale: 1, file: 'Nebel v1_2.webp', label: 'Nebel v1_2' },
  { scale: 1, file: 'Nebel v2_1 dicht.webp', label: 'Nebel v2_1 dicht' },
  { scale: 1, file: 'Nebel v2_1.webp', label: 'Nebel v2_1' },
  { scale: 1, file: 'Nebel v2_2 dicht.webp', label: 'Nebel v2_2 dicht' },
  { scale: 1, file: 'Nebel v2_2.webp', label: 'Nebel v2_2' },
  { scale: 1, file: 'Nebel v2_3 dicht.webp', label: 'Nebel v2_3 dicht' },
  { scale: 1, file: 'Nebel v2_3.webp', label: 'Nebel v2_3' },
  { scale: 1, file: 'Nebel v2_4 dicht.webp', label: 'Nebel v2_4 dicht' },
  { scale: 1, file: 'Nebel v2_4.webp', label: 'Nebel v2_4' },
  { scale: 1, file: 'Nebelschwade 1 transparent.webp', label: 'Nebelschwade 1 transparent' },
  { scale: 1, file: 'Nebelschwade 1.webp', label: 'Nebelschwade 1' },
  { scale: 1, file: 'Nebelschwade 2 transparent.webp', label: 'Nebelschwade 2 transparent' },
  { scale: 1, file: 'Nebelschwade 2.webp', label: 'Nebelschwade 2' },
  { scale: 1, file: 'Nebelschwade 3 transparent.webp', label: 'Nebelschwade 3 transparent' },
  { scale: 1, file: 'Nebelschwade 3.webp', label: 'Nebelschwade 3' },
  { scale: 1, file: 'Nebelschwade 4 transparent.webp', label: 'Nebelschwade 4 transparent' },
  { scale: 1, file: 'Nebelschwade 4.webp', label: 'Nebelschwade 4' },
  { scale: 1, file: 'Nebelschwade 5 transparent.webp', label: 'Nebelschwade 5 transparent' },
  { scale: 1, file: 'Nebelschwade 5.webp', label: 'Nebelschwade 5' },
  { scale: 1, file: 'Nebelschwade 6 transparent.webp', label: 'Nebelschwade 6 transparent' },
  { scale: 1, file: 'Nebelschwade 6.webp', label: 'Nebelschwade 6' },
  { scale: 1, file: 'Nebelschwade 7 transparent.webp', label: 'Nebelschwade 7 transparent' },
  { scale: 1, file: 'Nebelschwade 7.webp', label: 'Nebelschwade 7' },
  { scale: 1, file: 'Nelbel v1_1 dicht.webp', label: 'Nelbel v1_1 dicht' },
  { scale: 1, file: 'Nelbel v1_1.webp', label: 'Nelbel v1_1' },
  { scale: 1, file: 'Schienen.webp', label: 'Schienen' },
  { scale: 1, file: 'Schild Pfeil rechts.webp', label: 'Schild Pfeil rechts' },
  { scale: 1, file: 'Stein blockiert klein.webp', label: 'Stein blockiert klein' },
  { scale: 1, file: 'Stein blockiert.webp', label: 'Stein blockiert' },
  { scale: 1, file: 'Stein offen_.webp', label: 'Stein offen_' },
  { scale: 1, file: 'Stein_Moos.webp', label: 'Stein_Moos' },
  { scale: 1, file: 'Stein_Moosblume 1.webp', label: 'Stein_Moosblume 1' },
  { scale: 1, file: 'Textur Gepinselt Grün.webp', label: 'Textur Gepinselt Grün' },
  { scale: 1, file: 'Textur Gepinselt Sand.webp', label: 'Textur Gepinselt Sand' },
  { scale: 1, file: 'Textur Pepinselt Braun.webp', label: 'Textur Pepinselt Braun' },
  { scale: 1, file: 'Textur Pinsel Braun.webp', label: 'Textur Pinsel Braun' },
  { scale: 1, file: 'Textur Pinsel Grün.webp', label: 'Textur Pinsel Grün' },
  { scale: 1, file: 'Textur Pinsel Sand.webp', label: 'Textur Pinsel Sand' },
  { scale: 1, file: 'Textur Sprenkler Braun.webp', label: 'Textur Sprenkler Braun' },
  { scale: 1, file: 'Textur Sprenkler Grün.webp', label: 'Textur Sprenkler Grün' },
  { scale: 1, file: 'Textur Sprenkler Sand.webp', label: 'Textur Sprenkler Sand' },
  { scale: 1, file: 'Textur Spritzer Grün.webp', label: 'Textur Spritzer Grün' },
  { scale: 1, file: 'Trallalelo.webp', label: 'Trallalelo' },
  { scale: 1, file: 'Trockener Fleck_1.webp', label: 'Trockener Fleck_1' },
  { scale: 1, file: 'Trockener Fleck_2.webp', label: 'Trockener Fleck_2' },
  { scale: 1, file: 'Trockener Fleck_Kreis.webp', label: 'Trockener Fleck_Kreis' },
  { scale: 1, file: 'Trockener Fleck_Rechteck.webp', label: 'Trockener Fleck_Rechteck' },
  { scale: 1, file: 'icon_category_function_definition_locked.webp', label: 'icon_category_function_definition_locked' },
  { scale: 1, file: 'icon_category_function_definition_unlocked.webp', label: 'icon_category_function_definition_unlocked' },
  { scale: 1, file: 'icon_category_number_sets_locked.webp', label: 'icon_category_number_sets_locked' },
  { scale: 1, file: 'icon_category_number_sets_unlocked.webp', label: 'icon_category_number_sets_unlocked' },
  { scale: 1, file: 'icon_category_set_definition_locked.webp', label: 'icon_category_set_definition_locked' },
  { scale: 1, file: 'icon_category_set_definition_unlocked.webp', label: 'icon_category_set_definition_unlocked' },
  { scale: 1, file: 'icon_category_set_operations_locked.webp', label: 'icon_category_set_operations_locked' },
  { scale: 1, file: 'icon_category_set_operations_unlocked.webp', label: 'icon_category_set_operations_unlocked' },
  { scale: 1, file: 'icon_topic_sets_and_numbers_locked.webp', label: 'icon_topic_sets_and_numbers_locked' },
  { scale: 1, file: 'icon_topic_sets_and_numbers_unlocked.webp', label: 'icon_topic_sets_and_numbers_unlocked' },
  { scale: 1, file: 'schild Pfeil links.webp', label: 'schild Pfeil links' },
  { scale: 1, file: 'schild.webp', label: 'schild' },
]
