"""Fix task instructions and types

Revision ID: 0ba9e1a89f45
Revises: ece957c9591f
Create Date: 2025-09-11 01:04:12.612829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ba9e1a89f45'
down_revision: Union[str, None] = 'ece957c9591f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coursechapter_graph', 'predecessor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('task', sa.Column('task_type', postgresql.ENUM('AI', 'Multiple_Choice', name='tasktype', create_type=False), nullable=False))
    op.drop_column('task', 'solution')
    op.drop_column('task', 'task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('solution', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'task_type')
    op.alter_column('coursechapter_graph', 'predecessor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
