"""Add Task Log

Revision ID: 4b36442cb66f
Revises: 90fba0b4bccc
Create Date: 2025-08-14 21:53:31.619781
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa   # noqa: F401
import sqlmodel   # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '4b36442cb66f'
down_revision: Union[str, None] = '90fba0b4bccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'coursechapter_graph',
        'predecessor_id',
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.create_table(
        'task_log',
        sa.Column(
            'task_id',
            sa.Integer(),
            sa.ForeignKey('task.id', ondelete='CASCADE'),
            nullable=False,
        ),
        sa.Column(
            'user_uuid',
            sa.String(),
            sa.ForeignKey('user.user_uuid', ondelete='CASCADE'),
            nullable=False,
        ),
        sa.Column(
            'correct',
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            'date',
            sa.String(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'coursechapter_graph',
        'predecessor_id',
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_table('task_log')
    # ### end Alembic commands ###
