"""Add Task Log

Revision ID: 90fba0b4bccc
Revises: bfbe1ef4f65d
Create Date: 2025-08-14 21:30:07.617017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90fba0b4bccc'
down_revision: Union[str, None] = 'bfbe1ef4f65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paymentsuser')
    op.alter_column('coursechapter_graph', 'predecessor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tasklog', sa.Column('user_uuid', sa.String(), nullable=True))
    sa.Enum('PENDING', 'COMPLETED', 'ACTIVE', 'CANCELLED', 'FAILED', 'REFUNDED', name='paymentstatusenum').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'COMPLETED', 'ACTIVE', 'CANCELLED', 'FAILED', 'REFUNDED', name='paymentstatusenum').create(op.get_bind())
    op.drop_column('tasklog', 'user_uuid')
    op.alter_column('coursechapter_graph', 'predecessor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('paymentsuser',
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'ACTIVE', 'CANCELLED', 'FAILED', 'REFUNDED', name='paymentstatusenum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('provider_specific_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('payment_product_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('paymentsuser_org_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_product_id'], ['paymentsproduct.id'], name=op.f('paymentsuser_payment_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('paymentsuser_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('paymentsuser_pkey'))
    )
    # ### end Alembic commands ###
