"""Add Task Log

Revision ID: 90fba0b4bccc
Revises: bfbe1ef4f65d
Create Date: 2025-08-14 21:30:07.617017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90fba0b4bccc'
down_revision: Union[str, None] = 'bfbe1ef4f65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coursechapter_graph', 'predecessor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tasklog', sa.Column('user_uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklog', 'user_uuid')
    op.alter_column('coursechapter_graph', 'predecessor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
