"""Add trailstep extra data

Revision ID: bfbe1ef4f65d
Revises: ec6b2b783199
Create Date: 2025-06-03 12:25:35.064238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfbe1ef4f65d'
down_revision: Union[str, None] = 'ec6b2b783199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'assignment_task_complete',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=True),
        sa.Column('task_id', sa.Integer(), sa.ForeignKey('task.id', ondelete='CASCADE'), nullable=False,),
        sa.Column('activity_id', sa.Integer(), sa.ForeignKey('activity.id', ondelete='CASCADE'), nullable=False),
        sa.Column('course_id', sa.Integer(), sa.ForeignKey('course.id', ondelete='CASCADE'), nullable=False),
        sa.Column('org_id', sa.Integer(), sa.ForeignKey('organization.id', ondelete='CASCADE'), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id', ondelete='CASCADE'), nullable=False),
        sa.Column('complete', sa.Boolean(), nullable=False),
    )


def downgrade() -> None:
    op.drop_table('assignment_task_complete')