"""Make task instructions a dict

Revision ID: ece957c9591f
Revises: 4b36442cb66f
Create Date: 2025-09-10 21:41:18.369377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'ece957c9591f'
down_revision: Union[str, None] = '4b36442cb66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coursechapter_graph', 'predecessor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('task', sa.Column('task_instruction', sa.JSON(), nullable=True))
    op.drop_column('task', 'solution')
    op.drop_column('task', 'task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('solution', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'task_instruction')
    op.alter_column('coursechapter_graph', 'predecessor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
