"""Add gamification fields to user

Revision ID: f70bacaa06e5
Revises: 0ba9e1a89f45
Create Date: 2025-09-11 14:33:51.127662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f70bacaa06e5'
down_revision: Union[str, None] = '0ba9e1a89f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coursechapter_graph', 'predecessor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('task', sa.Column('task_type', postgresql.ENUM('AI', 'Multiple_Choice', name='tasktype', create_type=False), nullable=False))
    op.drop_column('task', 'task')
    op.drop_column('task', 'solution')
    op.add_column('user', sa.Column('coins', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('level_progress', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'level_progress')
    op.drop_column('user', 'level')
    op.drop_column('user', 'coins')
    op.add_column('task', sa.Column('solution', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('task', 'task_type')
    op.alter_column('coursechapter_graph', 'predecessor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
