name: Build and Push Docker Image

on:
  push:
    branches:
      - prod
      - staging

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for full commit history

      - name: Check if merged from dev
        id: check_dev
        run: |
          git fetch origin dev
          BASE_COMMIT=$(git merge-base HEAD origin/dev)
          if git log --oneline $BASE_COMMIT..HEAD | grep -q .; then
            echo "Merged from dev ✅"
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "Not merged from dev ❌"
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Get branch name
        id: vars
        run: |
          ref=${GITHUB_REF##*/}
          # Replace slashes with dashes for Docker tag compatibility
          tag=$(echo "$ref" | tr '/' '-')
          echo "branch_name=$tag" >> $GITHUB_OUTPUT


      - name: Deploy
        if: steps.check_dev.outputs.should_deploy == 'true'
        run: echo "🚀 Deploying..."

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/sk-platform:${{ steps.vars.outputs.branch_name }}.

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/sk-platform:${{ steps.vars.outputs.branch_name }}
